apiVersion: v1
kind: ConfigMap
metadata:
  name: unbora-backend-config
  namespace: unbora
data:
  PORT: "3001"
  ALLOWED_ORIGIN: "*"
  GROQ_MODEL: "openai/gpt-oss-120b"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service.unbora.svc.cluster.local:9092"
  UNBORA_KAFKA_ENABLED: "true"
  SUPERADMIN_NAME: "Super Admin"
