apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unbora

resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - kafka-kraft-deployment.yaml
  - kafka-ui-deployment.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - ingress.yaml
