package com.unbora.api.domain.sponsored.dto;

import com.unbora.api.domain.sponsored.BillingModel;
import com.unbora.api.domain.sponsored.PaymentStatus;
import com.unbora.api.domain.sponsored.PlanTier;

import java.math.BigDecimal;

public record SponsoredPlaceDto(
        String id,
        String name,
        String city,
        String region,
        String country,
        String type,
        String description,
        String benefitText,
        String categoryTags,
        String imageUrl,
        String mapsUrl,
        String address,
        String placeId,
        Double rating,
        String priceLevel,
        Boolean slotBoost,
        Boolean homeHighlight,
        Boolean active,
        Integer sortOrder,
        Long impressionsCount,
        Long clicksCount,
        BillingModel billingModel,
        PlanTier planTier,
        BigDecimal monthlyPrice,
        BigDecimal creditBalance,
        BigDecimal costPerClick,
        BigDecimal costPerImpression,
        BigDecimal dailyBudget,
        BigDecimal spentToday,
        BigDecimal totalSpent,
        PaymentStatus paymentStatus,
        String currentCycleStart,
        String nextBillingDate,
        String contactName,
        String contactPhone,
        String contactEmail,
        String cnpjCpf,
        String billingNotes,
        Boolean autoRenew,
        String createdAt,
        String updatedAt
) {}
