apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unbora-ingress
  namespace: unbora
spec:
  ingressClassName: traefik
  rules:
    - host: unbora.173.212.242.9.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unbora-backend-service
                port:
                  number: 3001
